android.useAndroidX=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
android.nonTransitiveRClass=true
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+UseG1GC -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx8g -XX:+UseG1GC
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
org.gradle.vfs.watch=true
ksp.incremental=true
android.bundle.enableUncompressedNativeLibs=true


# Flow Neuroengine
FLOW_NEURO_BASE_URL=https://api.flowneuroengine.com
FLOW_NEURO_API_KEY=dummy_key

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
